name: kin
description: "A Flutter app for staying connected with friends and family through calls."
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '3.10.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

  # State Management
  flutter_riverpod: 3.0.3

  # Authentication
  auth0_flutter: 1.14.0
  flutter_secure_storage: 9.2.4

  # Environment Configuration
  envied: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

  # Code Generation
  build_runner: 2.4.15
  envied_generator: 1.1.1

flutter:
  uses-material-design: true
