name: kin
description: "A Flutter app for staying connected with friends and family through calls."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '3.10.1'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

  # State Management
  flutter_riverpod: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
