name: kin
description: "A Flutter app for staying connected with friends and family through calls."
publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: '3.10.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: 1.0.8

  # State Management
  flutter_riverpod: 3.0.3

  # Authentication
  auth0_flutter: 1.14.0
  flutter_secure_storage: 9.2.4

  # Phone number input
  intl_phone_field: 3.2.0

  # Environment Configuration
  envied: 1.3.2
  posthog_flutter: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

  # Code Generation
  build_runner: 2.10.4
  envied_generator: 1.3.2

flutter:
  uses-material-design: true
  generate: true
